// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/comments.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/resources.tsx";
import * as $$0 from "./islands/CommentsForm.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/comments.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/resources.tsx": $3,
  },
  islands: {
    "./islands/CommentsForm.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
