// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/comments/[id].ts";
import * as $3 from "./routes/api/comments/index.ts";
import * as $4 from "./routes/comments.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/resources.tsx";
import * as $$0 from "./islands/CommentsForm.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/comments/[id].ts": $2,
    "./routes/api/comments/index.ts": $3,
    "./routes/comments.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/resources.tsx": $6,
  },
  islands: {
    "./islands/CommentsForm.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
